project:
  name: Spring Guard
  description: Spring Guard
  id_prefix: SG
  version: '1.0'
  created: 2026-04-15
  sdlc_root: .agent-sdlc/
  artifacts:
    - name: Implementation Specification
      short_name: impl spec
      location: impl-spec/
      name_pattern: "{id_prefix}-IML-{seq:05d}.md"
    - name: Backlog Item
      short_name: backlog item
      location: backlog-item/
      name_pattern: "{id_prefix}-BLG-{seq:05d}.md"
    - name: Requirement
      short_name: requirement
      location: requirement/
      name_pattern: "{id_prefix}-REQ-{seq:05d}.md"
    - name: Risk
      short_name: risk
      location: risk/
      name_pattern: "{id_prefix}-RSK-{seq:05d}.md"
  agents:
    - name: Rook
      session_id: 019d915e-9f68-78f3-a471-39d673f6e306
      type: Codex
      work_boundaries:
        - ./backend/src/main/java/uk/ac/ebi/spot/ols/controller/api/v1/V1SearchController.java
        - ./backend/src/main/java/uk/ac/ebi/spot/ols/controller/api/v1/V1IndividualController.java
        - ./backend/src/main/java/uk/ac/ebi/spot/ols/controller/api/v1/V1OntologyController.java
    - name: Kestrel
      session_id: 019d915e-24a7-7ef1-81fe-9a282f24cc41
      type: Codex
      work_boundaries:
        - ./backend/src/main/java/uk/ac/ebi/spot/ols/controller/api/v1/
        - ./backend/src/main/java/uk/ac/ebi/spot/ols/controller/api/v2/
        - ./.agents/skills/implementation-spec
        - ./.agents/skills/backlog-item
    - name: Heron
      session_id: 019d9095-b3ee-7801-b3eb-4168d47491fd
      type: Codex
      work_boundaries:
        - ./
        - /Users/leo.yung/.codex/config.toml
        - /Users/leo.yung/.codex/skills/codex-session-bridge
    # - name: Polly
    #   session_id: 019d4d29-bec4-7300-8669-1274fabf413e
    #   type: Codex
    #   work_boundaries:
    #     - ./tests
    #   status: inactive
    
